# includes/excludes all rules by default
default: true

# 4-space list indentation works best with MkDocs
MD007:
  indent: 2

# Remove line length limit - no one wants to hard wrap all their paragraphs
MD013: false

# Allow duplicate headers
MD024: false

# Allow inline HTML
MD033: false

# Allow fenced code blocks
MD046: false

# Allow first line in a file to not be a top-level heading
MD041: false
