FROM eligibility_server:latest

USER root

# install tooling: curl, git, jq, ssh
# install python tooling: pip, flake8, pre-commit
RUN apt-get update \
    && apt-get install -qq --no-install-recommends curl git jq ssh build-essential \
    && python -m pip install --upgrade pip

RUN pip install --no-cache-dir flake8 pre-commit coverage pytest

# install docs tooling:
COPY docs/requirements.txt docs/requirements.txt
RUN pip install --no-cache-dir -r docs/requirements.txt
