schedules:
  - cron: 0 10 * * * # timezone is UTC
    displayName: "Restart app services nightly"
    branches:
      include:
      - dev
    always: true

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - template: ../pipeline/restart.yml
    parameters:
      # path is relative to the template path (see line above)
      variable_file: ../mst/azure-vars.yml
