trigger:
  branches:
    include:
      - dev
      - test
      - prod
      - refs/tags/20??.??.?*-rc?*
      - refs/tags/20??.??.?*
  # only run for changes to Terraform files
  paths:
    include:
      - terraform/*

pr:
  branches:
    include:
      - "*"
  paths:
    include:
      - terraform/*

pool:
  vmImage: ubuntu-latest

stages:
  - template: ../pipeline/deploy.yml
    parameters:
      # path is relative to the template path (see line above)
      variable_file: ../sbmtd/azure-vars.yml
