name: Create GitHub release

on:
  push:
    tags:
      # release tags
      - "202[3-9].[0-9][0-9].[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # https://github.com/softprops/action-gh-release#permissions
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          generate_release_notes: true
